<?xml version="1.0" encoding="utf-8"?><Database Name="db_sistema" Class="sistemaDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=NOTEBOOK\SQLEXPRESS;Initial Catalog=db_sistema;Persist Security Info=True;User ID=sa" SettingsObjectName="Sistemas.DAL.Properties.Settings" SettingsPropertyName="db_sistemaConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.tb_categoria" Member="Categorias">
    <Type Name="Categorias">
      <Column Name="id_categoria" Member="Codigo" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="desc_categoria" Member="Descricao" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="Categorias_Produto" Member="Produtos" ThisKey="Codigo" OtherKey="CodigoCategoria" Type="Produto" />
    </Type>
  </Table>
  <Table Name="dbo.tb_produto" Member="Produtos">
    <Type Name="Produto">
      <Column Name="id_produto" Member="Codigo" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="desc_produto" Member="Descricao" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="valor" Type="System.Decimal" DbType="Decimal(25,2)" CanBeNull="true" />
      <Column Name="id_categoria" Member="CodigoCategoria" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Produto_ItensVenda" Member="ItensVendas" ThisKey="Codigo" OtherKey="CodigoProduto" Type="ItensVenda" />
      <Association Name="Categorias_Produto" Member="Categorias" ThisKey="CodigoCategoria" OtherKey="Codigo" Type="Categorias" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.tb_itens_venda" Member="ItensVendas">
    <Type Name="ItensVenda">
      <Column Name="quantidade" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="id_produto" Member="CodigoProduto" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="id_venda" Member="CodigoVenda" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="valor" Type="System.Decimal" DbType="Decimal(15,2) NOT NULL" CanBeNull="false" />
      <Column Name="id_item" Member="CodigoItem" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Association Name="Produto_ItensVenda" Member="Produto" ThisKey="CodigoProduto" OtherKey="Codigo" Type="Produto" IsForeignKey="true" />
      <Association Name="Venda_ItensVenda" Member="Venda" ThisKey="CodigoVenda" OtherKey="CodigoVenda" Type="Venda" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.tb_venda" Member="Vendas">
    <Type Name="Venda">
      <Column Name="id_venda" Member="CodigoVenda" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="valor" Type="System.Decimal" DbType="Decimal(15,2)" CanBeNull="true" />
      <Column Name="desconto" Type="System.Decimal" DbType="Decimal(15,2)" CanBeNull="true" />
      <Column Name="valor_pago" Member="valorPago" Type="System.Decimal" DbType="Decimal(15,2)" CanBeNull="true" />
      <Column Name="id_pessoa" Member="CodigoPessoa" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Venda_ItensVenda" Member="ItensVendas" ThisKey="CodigoVenda" OtherKey="CodigoVenda" Type="ItensVenda" />
      <Association Name="Venda_Contas_receber" Member="Contas_recebers" ThisKey="CodigoVenda" OtherKey="Codigo_venda" Type="Contas_receber" />
      <Association Name="Pessoas_Venda" Member="Pessoas" ThisKey="CodigoPessoa" OtherKey="CodigoPessoa" Type="Pessoas" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.tb_pessoas" Member="Pessoas">
    <Type Name="Pessoas">
      <Column Name="id_pessoa" Member="CodigoPessoa" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="desc_pessoa" Member="descricao" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="Pessoas_Venda" Member="Vendas" ThisKey="CodigoPessoa" OtherKey="CodigoPessoa" Type="Venda" />
    </Type>
  </Table>
  <Table Name="dbo.tb_usuario" Member="Usuarios">
    <Type Name="Usuarios">
      <Column Name="usuario" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="senha" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="id_pessoa" Member="CodigoPessoa" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.tb_status_pagamento" Member="status_pagamentos">
    <Type Name="status_pagamento">
      <Column Name="id_status" Member="codigo_status" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="status" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="status_pagamento_Contas_receber" Member="Contas_recebers" ThisKey="codigo_status" OtherKey="Codigo_status" Type="Contas_receber" />
    </Type>
  </Table>
  <Table Name="dbo.tb_contas_receber" Member="Contas_recebers">
    <Type Name="Contas_receber">
      <Column Name="id_conta" Member="codigo_conta" Storage="_codio_conta" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="data_compra" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="data_vencimento" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="data_pagamento" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="id_venda" Member="Codigo_venda" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="id_status" Member="Codigo_status" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="status_pagamento_Contas_receber" Member="status_pagamento" ThisKey="Codigo_status" OtherKey="codigo_status" Type="status_pagamento" IsForeignKey="true" />
      <Association Name="Venda_Contas_receber" Member="Venda" ThisKey="Codigo_venda" OtherKey="CodigoVenda" Type="Venda" IsForeignKey="true" />
    </Type>
  </Table>
</Database>